data:
  train_path: data/train.csv
  test_path: data/test.csv
  target: Response

train:
  test_size: 0.2
  random_state: 42
  shuffle: true

baseline_model:
  name: RandomForestClassifier
  params:
    criterion: gini
    max_depth: 10
    n_estimators: 50
  store_path: models/


prod_model:
  name: GradientBoostingClassifier
  params:
    max_depth: 10
    n_estimators: 50
  store_path: models/

